version: 2

sources:
  - name: fivetran_interview_db
    description: "this dataset includes covid infection among the country called indonesia"
    database: fivetran_interview_db
    schema: google_sheets
    tables:
      - name: covid_19_indonesia_samchristy_s
        
    

  